# ===============================
# CONFIGURATION DE LA BASE DE DONNÉES
# ===============================
spring.datasource.url=jdbc:postgresql://db.yvfvgodszapuawdprrkt.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Aurora17122004JoPi?
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURATION JPA/HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

# ===============================
# CONFIGURATION DU SERVEUR
# ===============================
server.port=${PORT:8080}

# ===============================
# CONFIGURATION DES LOGS
# ===============================
logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
